### PR TITLE
Upload my files

### PR DESCRIPTION
**Pull request by agatagruza**
Project T-Shirt is a design competition initiative created by fellow scholars of Secure and Private AI Challenge. In this submission you will see step by step process how team unstoppable created 87 images. Video with slide show available.

### CODE REVIEW

**Review by calincan2000 — APPROVED** [review]

**Review by calincan2000 — DISMISSED** [review]

**Comment by Shanmugapriya03** [comment]
Screenshot 2019-08-20 at 1 56 32 PM

**Comment by Shanmugapriya03** [comment]
Please do add your files and Rais PR again

**Review by kkech — CHANGES_REQUESTED** [review]
Hi @agatagruza ,

You have to upload your files in this repo and not just link your repo.

**Comment by agatagruza** [comment]
Created new pull: https://github.com/aksht94/UdacityOpenSource/pull/94

**Pull request closed without merging**
