### PR TITLE
Rejecting sarthak project because of affecting others file

### PR DESCRIPTION
**Pull request by ahkhalwai**
now u can check it

### CODE REVIEW

**Comment by ahkhalwai** [comment]
what we need to do ? can you explain me?

**Comment by ahkhalwai** [comment]
at list give us some solution rather than rejecting it, the only way it can solve the issue

**Comment by cibaca** [comment]
@ahkhalwai You need to ensure that only your folders is updated in files change no other folders should be visible as a change. I tried contacting Sarthak on slack but he is away. If you need any assistance raise on slack one of us who is available will assist you.

**Comment by ahkhalwai** [comment]
@cibaca sarthak is outside the town thats y i m here.. yes i already need assistance because if you guys dont accept his project then his time or work is lost 

i m not happy with management team .. they directly rejecting it without giving any solution for that

**Comment by cibaca** [comment]
@ahkhalwai Please connect with us for a solution, we need to know your steps to help you out and connect on slack. Here all of us are not notified of your message. Sarthak would have received email and notification on Github. 
Reason for rejection is mentioned that its modifying other project folders so that needs to be corrected

**Comment by ahkhalwai** [comment]
steps
1) fork the respo
2) clone the resp to the github desktop
3) then add project to the clone folder
4) then give commit the changes
5) then push origin to Github respo which i clone or fork respo
6) then request to pull
7) then expert guy reject the pull reject !! 

@calincan2000 @kkech

**Pull request closed without merging**
