### PR TITLE
Project MOST of @sg_aimlpros group, focuses on MOdeling and STatistic…

### PR DESCRIPTION
**Pull request by drvigneshwari**

### CODE REVIEW

**Review by kkech — CHANGES_REQUESTED** [review]
Hi @drvigneshwari ,

You change files that you do not own. Plz be careful. Make a new pull request and change only your files.

**Comment by drvigneshwari** [comment]
kkech I have changed my project AIMLPros only! Please let me know if there is anything need to done

**Comment by kkech** [comment]
> kkech I have changed my project AIMLPros only! Please let me know if there is anything need to done

No you do not. Check the photo.

Screenshot 2019-08-20 at 13 14 18

You are changing Antonio files too.

If you have a problem uploading your project, send me a pm in slack. I can even upload the project for you.

**Comment by drvigneshwari** [comment]
I am extremely sorry! I did not do it intentionally! 

This is the event log from android studio

3:31 PM	3 files committed: Project MOST of @sg_aimlpros group, focuses on MOdeling and STatistics. Its mission is to implement different models on the same dataset and provide statistics regarding the most accurate model for image processing through details collected from the models. The goal of this project is to classify rice diseases using a rice disease dataset on Kaggle.

3:33 PM	Push successful: Pushed AIMLPros to new branch origin/AIMLPros

**Comment by drvigneshwari** [comment]
Even here, the message is displayed as drvigneshwari wants to merge 1 commit into aksht94:master from drvigneshwari:AIMLPros

**Comment by kkech** [comment]
> Even here, the message is displayed as drvigneshwari wants to merge 1 commit into aksht94:master from drvigneshwari:AIMLPros

Plz send me a private message in slack. I will help you with the whole process.

**Pull request closed without merging**
