### PR TITLE
Upload my files

### PR DESCRIPTION
**Pull request by elementh11**
This is my Udacity's Facebook Secure and Private AI Challenge project

### CODE REVIEW

**Review by Sajjadmanal — APPROVED** [review]
Good Work.

**Review by Sajjadmanal — COMMENTED** [review]
Reviewed

**Review by Sajjadmanal — COMMENTED** [review]
Please add a proper readme file containing your name in contributors list.

**Comment by cibaca** [comment]
Please raise the pull request again and add the readme in your project folder

**Pull request merged**
