### PR TITLE
This is the research that I did during Udacity Challenge

### PR DESCRIPTION
**Pull request by agarwalanant**
I'm currently extending the research by developing a new algorithm which will reduce the large deep learning dataset into small ones

### CODE REVIEW

**Review by calincan2000 — DISMISSED** [review]

**Comment by agarwalanant** [comment]
I'm Anant Agarwal undergraduate student from India.

**Review by calincan2000 — COMMENTED** [review]
Can you add short description

**Comment by agarwalanant** [comment]
> Can you add short description
How to do that ? 
Should I add a README file in my brand and raise a pull request again ?

**Review by kkech — CHANGES_REQUESTED** [review]
Hi @agarwalanant ,

README file is missing. Plz add one.

**Review by kkech — APPROVED** [review]
Good work!

**Comment by agarwalanant** [comment]
I have added a short description of the project

**Review by ZSoumia — APPROVED** [review]

**Pull request merged**
