### PR TITLE
Mallikarjuna

### PR DESCRIPTION
**Pull request by MALLI7622**
I'm one of the Facebook Secure and Private AI Scholar. I had done a project on Fake News Detection using Natural Language Processing and Machine Learning. I had done Binary Classification and as well as six-way classification using different Machine Learning Classifiers they are 
1. **_Multinomial Naive Bayes Classifier_**
2. **_Passive Aggressive Classifier_**
3. **_Support Vector Classifier_**
4. **_Stochastic Gradient Descent Classifier_**
By training and testing repeatedly I had got **Multinomial Naive Bayes Classifier** is best for Binary Classification. And **Stochastic Gradient Descent Classifier** is best for six-way classification.

My project was helpful in finding Fake News during elections or campaigns in Social Media or News Channels.

### CODE REVIEW

**Review by calincan2000 — COMMENTED** [review]
Can you add description please?

**Comment by MALLI7622** [comment]
> Can you add description please?

Done 👍

**Review by calincan2000 — COMMENTED** [review]
Were can I see read me file?

**Comment by MALLI7622** [comment]
> Were can I see read me file?

I forget to add. Please give me some time

**Comment by MALLI7622** [comment]
> > Were can I see read me file?
> 
> I forget to add. Please give me some time

Sir How can add read me file. I don't know how

**Review by Shanmugapriya03 — APPROVED** [review]

**Comment by MALLI7622** [comment]
> > > Were can I see read me file?
> > 
> > 
> > I forget to add. Please give me some time
> 
> Sir How can add read me file. I don't know how

Done 👍

**Comment by MALLI7622** [comment]
> Were can I see read me file?

Done 👍

**Pull request merged**
