### PR TITLE
Upload my files

### PR DESCRIPTION
**Pull request by jess-s**
Udacity/Facebook Secure and Private AI Challenge

### CODE REVIEW

**Review by kkech — DISMISSED** [review]
I see that this is a group project. You have to name the root folder as your project name.

Only individual projects have to be named as your slack name.

**Comment by jess-s** [comment]
What is the easiest way to do that or do I need to start over with the whole process?  (I'm not totally new to github, but this is the most complex thing I've done in github so far!)

**Comment by kkech** [comment]
> What is the easiest way to do that or do I need to start over with the whole process? (I'm not totally new to github, but this is the most complex thing I've done in github so far!)

I think the best is to start over with the whole process. I can help you with that if you have any questions.

**Comment by jess-s** [comment]
I re-submitted with the updated folder name.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Review by ZSoumia — APPROVED** [review]
Well Done Changing the name of the folder .

**Review by ZSoumia — APPROVED** [review]

**Pull request merged**
