### PR TITLE
Upload my files

### PR DESCRIPTION
**Pull request by ahirsarthak**
I'm from udacity’s facebook challenge

### CODE REVIEW

**Review by calincan2000 — DISMISSED** [review]

**Review by calincan2000 — APPROVED** [review]

**Review by calincan2000 — DISMISSED** [review]

**Review by kkech — CHANGES_REQUESTED** [review]
Hi @sarthakahir,

Personality_detection_from_text_using_nlp/dataset1/mbti_1.csv must be under his slack name folder.

Plz change that.

**Comment by ahirsarthak** [comment]
I don't have any file named after this.

**Comment by kkech** [comment]
Yes, check your commit.

Here is a photo.

Screenshot 2019-08-19 at 14 40 13

**Comment by ahirsarthak** [comment]
That's not under my projects.
Mine is under sarthak ahir/Machine_learning.Taxi.Fare

**Comment by ahirsarthak** [comment]
mine is sarthak ahir/maching_learning.Taxi.Fare

**Comment by kkech** [comment]
You have updated all the files in one single commit. I cannot approve specific files, over a commit. I think the best is to fork this project and follow the instructions. Be careful, you have to change only your files.

If you still have a problem, you can contact me in slack. My username is kkech.

**Pull request closed without merging**
