### PR TITLE
Project T-Shirt is a design competition initiative created by fellow …

### PR DESCRIPTION
**Pull request by agatagruza**
Project T-Shirt is a design competition initiative created by fellow scholars of Secure and Private AI Challenge. In this submission you will see step by step process how team unstoppable created 87 images. Video with slide show available.

### CODE REVIEW

**Review by kkech — CHANGES_REQUESTED** [review]
Hi @agatagruza ,

You change other files, so plz be more careful with that. If you follow the instructions and still faces a problem, you can send me a message in slack. I can upload the project for you. My name in slack is kkech.

**Review by gargarchit — COMMENTED** [review]
@agatagruza I see that You have changed file of Antonio Please correct that

**Review by gargarchit — APPROVED** [review]
Blank file creating issue I will handle

**Comment by kkech** [comment]
I uploaded this project in another PR.

**Pull request closed without merging**
