### PR TITLE
Upload my files

### PR DESCRIPTION
**Pull request by bharatnishant**
Requesting to upload my project Network Intrusion Detection System using PyTorch, for Project Showcase Challenge for Secure and Private AI Scholarship by Udacity and Facebook

### CODE REVIEW

**Review by calincan2000 — DISMISSED** [review]

**Review by Shanmugapriya03 — CHANGES_REQUESTED** [review]
You have changed another person's file please do change it back

**Comment by Shanmugapriya03** [comment]
Screenshot 2019-08-20 at 2 10 09 PM

**Comment by bharatnishant** [comment]
Which changes I do need to do @Shanmugapriya03?

**Comment by gargarchit** [comment]
The files are there https://github.com/aksht94/UdacityOpenSource/tree/master/Network%20Intrusion%20Detection%20using%20PyTorch
Thanks @bharatnishant

**Pull request closed without merging**
