### PR TITLE
Sarthakahir

### PR DESCRIPTION
**Pull request by ghost**
I'm from udacity’s facebook challenge

### CODE REVIEW

**Review by calincan2000 — DISMISSED** [review]

**Comment by ghost** [comment]
what  changed?

**Review by cibaca — CHANGES_REQUESTED** [review]
@sarthakahir  Your pull request is affecting others project folder as well. Ensure to pull latest code while forking and then add your files for pull request. Kindly check once we can see 958 files updated

**Comment by gargarchit** [comment]
@sarthakahir You need to save your files and pull the this updated repo as you are 11 commits behind for now 
You can also close this pull request and make a new one

**Comment by ahkhalwai** [comment]
we did in a proper manner if you guys not give us a proper solution, so how we can learn?

**Pull request closed without merging**
